{
 "title": "Golden signals - skprom",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "model_version",
    "query": {
     "query": "label_values(request_count_total, model_version)"
    }
   },
   {
    "name": "impute_features",
    "query": {
     "query": "label_values(skprom_imputed_total, feature)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(request_latency_seconds_bucket{model_version=\"${model_version}\"}[$__interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "description": "Number of requests per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(request_count_total{model_version=\"${model_version}\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Error rate (ratio of total requests)",
   "type": "timeseries",
   "description": "Number of errors in the requests",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(request_error_total{model_version=\"${model_version}\"}[$__interval]) / rate(request_count_total{model_version=\"${model_version}\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Response distribution",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(response_distribution_bucket{le!=\"+Inf\", model_version=\"${model_version}\"}[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Unknown Categories", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Region",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(skprom_model_categorical_total{feature=\"region\", category=\"missing\"}[$__interval])"
    }
   ]
  },
  {
   "title": "top_pack",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(skprom_model_categorical_total{feature=\"top_pack\", category=\"missing\"}[$__interval])"
    }
   ]
  },
  { "title": "Imputer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Mutant",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(skprom_imputed_total{feature=\"montant\"}[$__interval])"
    }
   ]
  },
  {
   "title": "frequence",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(skprom_imputed_total{feature=\"frequence_rech\"}[$__interval])"
    }
   ]
  },
  {
   "title": "revenue",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(skprom_imputed_total{feature=\"revenue\"}[$__interval])"
    }
   ]
  },
  {
   "title": "arpu_segment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(skprom_imputed_total{feature=\"arpu_segment\"}[$__interval])"
    }
   ]
  },
  {
   "title": "data_volume",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(skprom_imputed_total{feature=\"data_volume\"}[$__interval])"
    }
   ]
  },
  {
   "title": "on_net",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(skprom_imputed_total{feature=\"on_net\"}[$__interval])"
    }
   ]
  }
 ]
}